databases:
  - name: timetrackdb
    plan: free
    databaseName: timetrack
    user: timetrack

services:
  - type: web
    name: timetrack-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn timetrack.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DEBUG
        value: "False" 