# Generated by Django 5.1 on 2025-01-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveConstraint(
            model_name='workermachine',
            name='unique_active_worker_machine',
        ),
    ]
