# Generated by Django 5.1 on 2025-01-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('DRILLING', 'Sondaj'), ('MOVING', 'Nakliye'), ('MAINTENANCE', 'Bakım'), ('IDLE', 'Boşta'), ('SETUP', 'Kurulum')], default='IDLE', help_text='Makinenin mevcut durumu', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='workermachine',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('worker',), name='unique_active_worker'),
        ),
    ]
