# Generated by Django 5.1.5 on 2025-02-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_shift_end_location_shift_start_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='report_image',
            field=models.ImageField(help_text='Vardiya rapor defteri fotoğrafı', null=True, upload_to='shift_reports/'),
        ),
    ]
