# Generated by Django 5.1.5 on 2025-02-03 15:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Malzeme Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Miktar')),
                ('unit', models.CharField(choices=[('ADET', 'Adet'), ('KG', 'Kilogram'), ('LT', 'Litre'), ('MT', 'Metre')], default='ADET', max_length=50, verbose_name='Birim')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory/', verbose_name='Fotoğraf')),
                ('min_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Miktar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stok Kalemi',
                'verbose_name_plural': 'Stok Kalemleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miktar')),
                ('transaction_type', models.CharField(choices=[('IN', 'Giriş'), ('OUT', 'Çıkış')], max_length=3, verbose_name='İşlem Tipi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventoryitem', verbose_name='Malzeme')),
            ],
            options={
                'verbose_name': 'Stok Hareketi',
                'verbose_name_plural': 'Stok Hareketleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
